/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KdsRouteImport } from './routes/kds'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as QrTableRouteImport } from './routes/qr.$table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KdsRoute = KdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const QrTableRoute = QrTableRouteImport.update({
  id: '/qr/$table',
  path: '/qr/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kds': typeof KdsRoute
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/styleguide': typeof StyleguideRoute
  '/tables': typeof TablesRoute
  '/qr/$table': typeof QrTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kds': typeof KdsRoute
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/styleguide': typeof StyleguideRoute
  '/tables': typeof TablesRoute
  '/qr/$table': typeof QrTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kds': typeof KdsRoute
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/styleguide': typeof StyleguideRoute
  '/tables': typeof TablesRoute
  '/qr/$table': typeof QrTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/kds'
    | '/menu'
    | '/onboarding'
    | '/pos'
    | '/pricing'
    | '/settings'
    | '/styleguide'
    | '/tables'
    | '/qr/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/kds'
    | '/menu'
    | '/onboarding'
    | '/pos'
    | '/pricing'
    | '/settings'
    | '/styleguide'
    | '/tables'
    | '/qr/$table'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/kds'
    | '/menu'
    | '/onboarding'
    | '/pos'
    | '/pricing'
    | '/settings'
    | '/styleguide'
    | '/tables'
    | '/qr/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  KdsRoute: typeof KdsRoute
  MenuRoute: typeof MenuRoute
  OnboardingRoute: typeof OnboardingRoute
  PosRoute: typeof PosRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  StyleguideRoute: typeof StyleguideRoute
  TablesRoute: typeof TablesRoute
  QrTableRoute: typeof QrTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kds': {
      id: '/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof KdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$table': {
      id: '/qr/$table'
      path: '/qr/$table'
      fullPath: '/qr/$table'
      preLoaderRoute: typeof QrTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  KdsRoute: KdsRoute,
  MenuRoute: MenuRoute,
  OnboardingRoute: OnboardingRoute,
  PosRoute: PosRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  StyleguideRoute: StyleguideRoute,
  TablesRoute: TablesRoute,
  QrTableRoute: QrTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
